# Generated by Django 2.2.5 on 2019-12-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wh',
            name='descrip',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wh',
            name='temperature',
            field=models.CharField(default='hi', max_length=10),
            preserve_default=False,
        ),
    ]
