# Generated by Django 2.2.5 on 2019-12-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20191213_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='wh',
            name='icon',
            field=models.CharField(default='hii', max_length=10),
            preserve_default=False,
        ),
    ]
